****
**Task 2: Tools for Data Science** 

> Tina Garg, Ananya Burli, Aniket Pokle



In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics 
from sklearn.naive_bayes import GaussianNB

info=datasets.load_iris()
#print(info.data)
#print(info.target)
#print(info.feature_names)

In [ ]:
X_df = pd.DataFrame(info.data,columns=info.feature_names) 
Y_df = pd.DataFrame(info.target)
#X_df.head(5)

In [ ]:
X_df.isna().sum() #checking if there are missing values, which might help in feature selection.

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
dtype: int64

In [ ]:
X_df_three = X_df.drop('petal width (cm)', axis=1) #selecting three out of the four features
Y_df_three = np.ravel(Y_df)

In [ ]:
X_df_three.head()

sepal length (cm)  sepal width (cm)  petal length (cm)
0                5.1               3.5                1.4
1                4.9               3.0                1.4
2                4.7               3.2                1.3
3                4.6               3.1                1.5
4                5.0               3.6                1.4

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X_df_three, Y_df_three, test_size=0.2, random_state=3)
X_train.head()

sepal length (cm)  sepal width (cm)  petal length (cm)
14                 5.8               4.0                1.2
24                 4.8               3.4                1.9
139                6.9               3.1                5.4
58                 6.6               2.9                4.6
8                  4.4               2.9                1.4

Part 1: Logistic Regression


In [ ]:
reg = linear_model.LogisticRegression()
reg.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
reg.coef_

array([[-0.49873473,  0.93504057, -2.63658259],
       [ 0.58485716, -0.44563482, -0.56467925],
       [-0.08612243, -0.48940575,  3.20126184]])

In [ ]:
Y_pred = reg.predict(X_test)
Y_pred

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 2, 0, 1, 2,
       2, 1, 0, 2, 2, 1, 1, 1])

In [ ]:
error = metrics.mean_squared_error(Y_pred,Y_test)
accuracy = metrics.accuracy_score(Y_pred, Y_test)

print(f'Accuracy using Linear Regression model is {accuracy*100}%')
print(f'Error in training the model is {error*100}%')

Accuracy using Linear Regression model is 93.33333333333333%
Error in training the model is 6.666666666666667%


Part 2: Using Gaussian Naive Bayes to calculate accuracy


In [ ]:
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
Y_gnb_pred = gnb.predict(X_test)
Y_gnb_pred

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 2,
       2, 2, 0, 2, 2, 1, 1, 2])

In [ ]:
accuracy_gnb = metrics.accuracy_score(Y_gnb_pred, Y_test)

print(f'Accuracy using the Gaussian Naive Bayes model is {accuracy_gnb*100}%')

Accuracy using the Gaussian Naive Bayes model is 86.66666666666667%


Part 3: Checking accuracy with more features


In [ ]:
X_df = pd.DataFrame(info.data,columns=info.feature_names) 
Y_df = pd.DataFrame(info.target)
X_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
X_df_full = X_df
Y_df_full = np.ravel(Y_df)
X_df_full.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
X_df_2 = X_df.copy()
  
# Max Scaling
for col in X_df_2.columns:
    X_df_2[col] = X_df_2[col]/ X_df_2[col].abs().max()
    
X_df_2.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0           0.645570          0.795455           0.202899              0.08
1           0.620253          0.681818           0.202899              0.08
2           0.594937          0.727273           0.188406              0.08
3           0.582278          0.704545           0.217391              0.08
4           0.632911          0.818182           0.202899              0.08

In [ ]:
X_train2,X_test2,Y_train2,Y_test2 = train_test_split(X_df_2, Y_df_full, test_size=0.2, random_state=3)
X_train2.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
14            0.734177          0.909091           0.173913              0.08
24            0.607595          0.772727           0.275362              0.08
139           0.873418          0.704545           0.782609              0.84
58            0.835443          0.659091           0.666667              0.52
8             0.556962          0.659091           0.202899              0.08


Part 3a: Logistic Regression with more feaatures


In [ ]:
reg2= linear_model.LogisticRegression()
reg2.fit(X_train2,Y_train2)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
reg2.coef_
Y_pred2 = reg2.predict(X_test2)
Y_pred2

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 2, 0, 2, 2,
       2, 1, 0, 2, 1, 1, 1, 1])

In [ ]:
error2 = metrics.mean_squared_error(Y_pred2,Y_test2)
accuracy2 = metrics.accuracy_score(Y_pred2, Y_test2)

print(f'Accuracy using Linear Regression model is {accuracy2*100}%')
print(f'Error in training the model is {error2*100}%')

Accuracy using Linear Regression model is 96.66666666666667%
Error in training the model is 3.3333333333333335%


The accuracy increases when we use the 4th feature.

Having more features does not always improve the accuracy. Sometimes it leads to overfitting, which doesn't respond well to new data. Increasing the number of features also increases the learning time, which may be undesirable. If it will learn for too long, the model will become more prone to overfitting due to the presence of noise and less useful details.



Part 3b: Gaussian Naive Bayes with more features

In [ ]:
gnb2 = GaussianNB()
gnb2.fit(X_train2, Y_train2)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
Y_gnb_pred2 = gnb2.predict(X_test2)
Y_gnb_pred2

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 2, 0, 2, 2,
       2, 1, 0, 2, 1, 1, 1, 1])

In [ ]:
accuracy_gnb2 = metrics.accuracy_score(Y_gnb_pred2, Y_test2)

print(f'Accuracy using the Gaussian Naive Bayes model is {accuracy_gnb2*100}%')

Accuracy using the Gaussian Naive Bayes model is 96.66666666666667%


Note that in this case both methods yield results with the same accuracy. The correct point to stop (with feature selection) is once the error starts increasing again. We believe this is achieved with practice. 

Recursive Feature Elimination is a non-manual way to select the features with good performance (recursively, obviously). 



```
from sklearn.feature_selection import RFE
```



Thank you.